baseURL = "https://wonderful-jackson-eb7e56.netlify.app/"
languageCode = "en-us"
title = "ReadAlongs"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  slogan = "ReadAlongs"
  sloganSubtext = "Align your text and audio"
  favicon = ""
  site_logo = ""
  description = "Align your text and audio"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/bg.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]
  body_classes = "lato"
